# Generated by Django 4.2.7 on 2023-12-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=10)),
                ('rating', models.IntegerField(default=3)),
                ('image', models.ImageField(upload_to='covers/')),
            ],
        ),
    ]
