# Generated by Django 4.2.7 on 2023-12-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_section_alter_courseinfo_image_sectionelement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='sectionelement',
            old_name='section_id',
            new_name='section',
        ),
    ]
