# Generated by Django 4.2.7 on 2023-12-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_course_id_section_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='image',
            field=models.ImageField(default='courses_info/covers/default.jpg', upload_to='courses_info/covers/'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
