# Generated by Django 4.2.7 on 2023-12-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseinfo_url_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sectionelement',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
