# Generated by Django 4.2.7 on 2023-12-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_section_order_sectionelement_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionelement',
            name='description',
            field=models.TextField(default='dwefaf'),
            preserve_default=False,
        ),
    ]
